- name: Gaming
  columns:
    - size: full
      widgets:
        - type: clock
          hour-format: 24h
        - type: group
          widgets:
            - type: reddit
              show-thumbnails: true
              subreddit: pcgaming
            - type: reddit
              subreddit: games
        - type: videos
          style: grid-cards
          collapse-after-rows: 3
          channels:
            - UC3NPuQGUQ8HDPL2LtWPlHeA # sangtraan
            - UCfU42vu0J0xk6oa2S0SP-Eg # HK15
            - UCog3Th5YoH5cuosdwaavGFg # desmondvu1
            - UCJojBppsLbhkaQ_DySRWM-A # BLV Thanh Tung
            - UCpnQwjzvDm1MOMtZV2zkVpA # Liên Quân Mobile eSports-Garena
            - UCTQVIBMJLkipI2Rc1qjTyDw # Quân Fbz